/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Sun Oct  7 08:17:00 2018. */

#ifndef PB_LIGHTSWITCHDATA_PB_H_INCLUDED
#define PB_LIGHTSWITCHDATA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Time {
    bool has_seconds;
    int64_t seconds;
/* @@protoc_insertion_point(struct:Time) */
} Time;

typedef struct _LightSwitchState {
    bool has_lighIsOn;
    bool lighIsOn;
    pb_callback_t scheduledActions;
    bool has_timeStampSent;
    Time timeStampSent;
/* @@protoc_insertion_point(struct:LightSwitchState) */
} LightSwitchState;

typedef struct _ScheduledAction {
    bool has_turnLightOn;
    bool turnLightOn;
    bool has_timeToAct;
    Time timeToAct;
/* @@protoc_insertion_point(struct:ScheduledAction) */
} ScheduledAction;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Time_init_default                        {false, 0}
#define LightSwitchState_init_default            {false, 0, {{NULL}, NULL}, false, Time_init_default}
#define ScheduledAction_init_default             {false, 0, false, Time_init_default}
#define Time_init_zero                           {false, 0}
#define LightSwitchState_init_zero               {false, 0, {{NULL}, NULL}, false, Time_init_zero}
#define ScheduledAction_init_zero                {false, 0, false, Time_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Time_seconds_tag                         1
#define LightSwitchState_lighIsOn_tag            1
#define LightSwitchState_scheduledActions_tag    2
#define LightSwitchState_timeStampSent_tag       3
#define ScheduledAction_turnLightOn_tag          1
#define ScheduledAction_timeToAct_tag            2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Time_fields[2];
extern const pb_field_t LightSwitchState_fields[4];
extern const pb_field_t ScheduledAction_fields[3];

/* Maximum encoded size of messages (where known) */
#define Time_size                                11
/* LightSwitchState_size depends on runtime parameters */
#define ScheduledAction_size                     15

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LIGHTSWITCHDATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
