/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: LightSwitchData.pb3 */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "LightSwitchData.pb3.pb-c.h"
void   time__init
                     (Time         *message)
{
  static const Time init_value = TIME__INIT;
  *message = init_value;
}
size_t time__get_packed_size
                     (const Time *message)
{
  assert(message->base.descriptor == &time__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time__pack
                     (const Time *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time__pack_to_buffer
                     (const Time *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Time *
       time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Time *)
     protobuf_c_message_unpack (&time__descriptor,
                                allocator, len, data);
}
void   time__free_unpacked
                     (Time *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   light_switch_state__init
                     (LightSwitchState         *message)
{
  static const LightSwitchState init_value = LIGHT_SWITCH_STATE__INIT;
  *message = init_value;
}
size_t light_switch_state__get_packed_size
                     (const LightSwitchState *message)
{
  assert(message->base.descriptor == &light_switch_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t light_switch_state__pack
                     (const LightSwitchState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &light_switch_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t light_switch_state__pack_to_buffer
                     (const LightSwitchState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &light_switch_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LightSwitchState *
       light_switch_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LightSwitchState *)
     protobuf_c_message_unpack (&light_switch_state__descriptor,
                                allocator, len, data);
}
void   light_switch_state__free_unpacked
                     (LightSwitchState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &light_switch_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scheduled_action__init
                     (ScheduledAction         *message)
{
  static const ScheduledAction init_value = SCHEDULED_ACTION__INIT;
  *message = init_value;
}
size_t scheduled_action__get_packed_size
                     (const ScheduledAction *message)
{
  assert(message->base.descriptor == &scheduled_action__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scheduled_action__pack
                     (const ScheduledAction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scheduled_action__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scheduled_action__pack_to_buffer
                     (const ScheduledAction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scheduled_action__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScheduledAction *
       scheduled_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScheduledAction *)
     protobuf_c_message_unpack (&scheduled_action__descriptor,
                                allocator, len, data);
}
void   scheduled_action__free_unpacked
                     (ScheduledAction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scheduled_action__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor time__field_descriptors[1] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Time, has_seconds),
    offsetof(Time, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time__field_indices_by_name[] = {
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Time",
  "Time",
  "Time",
  "",
  sizeof(Time),
  1,
  time__field_descriptors,
  time__field_indices_by_name,
  1,  time__number_ranges,
  (ProtobufCMessageInit) time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor light_switch_state__field_descriptors[3] =
{
  {
    "lighIsOn",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(LightSwitchState, has_lighison),
    offsetof(LightSwitchState, lighison),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scheduledActions",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LightSwitchState, n_scheduledactions),
    offsetof(LightSwitchState, scheduledactions),
    &scheduled_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeStampSent",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LightSwitchState, timestampsent),
    &time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned light_switch_state__field_indices_by_name[] = {
  0,   /* field[0] = lighIsOn */
  1,   /* field[1] = scheduledActions */
  2,   /* field[2] = timeStampSent */
};
static const ProtobufCIntRange light_switch_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor light_switch_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LightSwitchState",
  "LightSwitchState",
  "LightSwitchState",
  "",
  sizeof(LightSwitchState),
  3,
  light_switch_state__field_descriptors,
  light_switch_state__field_indices_by_name,
  1,  light_switch_state__number_ranges,
  (ProtobufCMessageInit) light_switch_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scheduled_action__field_descriptors[2] =
{
  {
    "turnLightOn",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ScheduledAction, has_turnlighton),
    offsetof(ScheduledAction, turnlighton),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeToAct",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ScheduledAction, timetoact),
    &time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scheduled_action__field_indices_by_name[] = {
  1,   /* field[1] = timeToAct */
  0,   /* field[0] = turnLightOn */
};
static const ProtobufCIntRange scheduled_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor scheduled_action__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScheduledAction",
  "ScheduledAction",
  "ScheduledAction",
  "",
  sizeof(ScheduledAction),
  2,
  scheduled_action__field_descriptors,
  scheduled_action__field_indices_by_name,
  1,  scheduled_action__number_ranges,
  (ProtobufCMessageInit) scheduled_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
